version: '3.7'

services:
  web:
    build: api/
    working_dir: /api
    command: python ./manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db

  scraper:
    build: scraping/
    working_dir: /scraping
    command: python ./parser.py
    depends_on:
      - web

  db:
    image: postgres:12.0-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db

volumes:
  postgres_data: